name: WCSS - Build Apptainer Image
on:
  workflow_dispatch:
    inputs:
      dbms:
        description: 'Database engine to build the image for (sqlite, mysql, postgresql, mariadb)'
        required: true
        default: 'sqlite'
      use_old_squirrel:
        description: 'Whether to use the old Squirrel repository for building (1 for old, 0 for new)'
        required: true
        default: '0'
jobs:
  build-apptainer-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSH command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          command_timeout: '60m'
          script: |
            DBMS="${{ github.event.inputs.dbms }}"
            USE_OLD_SQUIRREL="${{ github.event.inputs.use_old_squirrel }}"
            
            dirName=${{ github.actor }}-$DBMS

            # Clean up existing directory
            rm -rf ~/"$dirName"

            # Clone repository
            git clone -b ${{ github.ref_name }} https://github.com/syurima/Squirrel.git
            mv ~/Squirrel ~/"$dirName"
            cd ~/"$dirName"

            # Run Slurm Build Job
            echo "Building Apptainer image..."
            JOB_ID=$(sbatch --wait wcss_build.sh "$DBMS" "$USE_OLD_SQUIRREL" | awk '{print $4}')
            SLURM_EXIT_CODE=$?          # <-- capture the exit status of sbatch (i.e. the job)
            BUILD_EXIT_STATUS=$(grep -oP 'exit status \K\d+' slurm-$JOB_ID.out || echo 0)

            # Print the job output
            echo "Job output:"
            cat slurm-$JOB_ID.out

            # Fail the step if the Slurm job failed
            if [[ $SLURM_EXIT_CODE -ne 0 || $BUILD_EXIT_STATUS -ne 0 ]]; then
              echo "Slurm job failed."
              exit 1
            fi

            echo "Slurm job finished successfully"