name: WCSS - Run Fuzzing Job
on:
  workflow_dispatch:
    inputs:
      dbms:
        description: 'Database engine to run the fuzzing job for'
        required: true
        default: 'sqlite'
      max_runtime:
        description: 'Maximum runtime for the Slurm job (format HH:MM:SS)'
        required: true
        default: '0:05:00'
      use_old_squirrel:
        description: 'Whether to use the image from the old Squirrel repository (1 for old, 0 for new)'
        required: true
        default: '0'
      slurm_cores:
        description: 'Number of CPU cores to allocate for the Slurm job'
        required: true
        default: '32'
      afl_workers:
        description: 'Number of AFL++ worker processes to use (set to 0 to auto-detect based on SLURM_CORES). do not set this to a value higher than the number of cores allocated for the Slurm job.'
        required: true
        default: '0'
      allocated_RAM:
        description: 'Amount of RAM to allocate for the Slurm job (in GB)'
        required: true
        default: '32'
jobs:
  run-fuzzing:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSH command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          command_timeout: '60m'
          script: |
            DBMS="${{ github.event.inputs.dbms }}"
            MAX_RUNTIME="${{ github.event.inputs.max_runtime }}"
            USE_OLD_SQUIRREL="${{ github.event.inputs.use_old_squirrel }}"
            SLURM_CORES="${{ github.event.inputs.slurm_cores }}"
            AFL_WORKERS="${{ github.event.inputs.afl_workers }}"
            RAM="${{ github.event.inputs.allocated_RAM }}gb"

            dirName=${{ github.actor }}-$DBMS-run-$USE_OLD_SQUIRREL

            cd ~/"$dirName"
            
            # !! YOU NEED TO RUN THE BUILD SCRIPT BEFORE THIS ONE TO BUILD THE APPTAINER IMAGE. 
            # This script assumes that the image is already built and available in the current directory.

            # Submit job – pass both DBMS and max runtime
            echo "Running Slurm job..."
            JOB_ID=$(sbatch --wait --mem="$RAM" --time="$MAX_RUNTIME" -c"$SLURM_CORES" ~/images/wcss_run.sh "$DBMS" "$USE_OLD_SQUIRREL" "$AFL_WORKERS" | awk '{print $4}')
            SLURM_EXIT_CODE=$?
            RUN_EXIT_STATUS=$(grep -oP 'exit status \K\d+' slurm-$JOB_ID.out || echo 0)

            # Print the job output
            echo "Job output:"
            cat slurm-$JOB_ID.out

            # Fail the step if the Slurm job failed
            if [[ $SLURM_EXIT_CODE -ne 0 || $RUN_EXIT_STATUS -ne 0 ]]; then
              echo "Slurm job failed."
              exit 1
            fi

            # Clean up the temporary directory
            cd ..
            rm -rf ~/"$dirName"

            echo "Slurm job finished successfully."