name: WCSS - Run Fuzzing Job
on:
  workflow_dispatch:
    inputs:
      dbms:
        description: 'Database engine to run the fuzzing job for'
        required: true
        default: 'sqlite'
      max_runtime:
        description: 'Maximum runtime for the Slurm job (format HH:MM:SS)'
        required: true
        default: '0:05:00'
jobs:
  run-fuzzing:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSH command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          command_timeout: '60m'
          script: |
            DBMS="${{ github.event.inputs.dbms }}"
            MAX_RUNTIME="${{ github.event.inputs.max_runtime }}"

            dirName=${{ github.actor }}-$DBMS

            cd ~/"$dirName"
            
            # !! YOU NEED TO RUN THE BUILD SCRIPT BEFORE THIS ONE TO BUILD THE APPTAINER IMAGE. 
            # This script assumes that the image is already built and available in the current directory.

            # Submit job – pass both DBMS and max runtime
            echo "Running Slurm job..."
            JOB_ID=$(sbatch --wait --time="$MAX_RUNTIME" wcss_run.sh "$DBMS" | awk '{print $4}')
            SLURM_EXIT_CODE=$?
            RUN_EXIT_STATUS=$(grep -oP 'exit status \K\d+' slurm-$JOB_ID.out || echo 0)

            # Print the job output
            echo "Job output:"
            cat slurm-$JOB_ID.out

            # Fail the step if the Slurm job failed
            if [[ $SLURM_EXIT_CODE -ne 0 || $RUN_EXIT_STATUS -ne 0 ]]; then
              echo "Slurm job failed."
              exit 1
            fi

            echo "Slurm job finished successfully."